Create a profile list
rustminded/recruit-rust pull request #13
Opened 2021-03-02 13:37 UTC by yozhgoor

2021-03-02 18:01 UTC, cecton requested changes
A bit of work to do sorry :pray:

2021-03-02 18:01 UTC, cecton commented on src/app.rs
> +                        {profile_list}
The profile list should not be shown while you are consulting a profile.

2021-03-02 19:20 UTC, cecton commented on src/app.rs
> +            .map(|(_x, y)| y)
Not solved. Fix it

2021-03-02 19:22 UTC, cecton commented on src/app.rs
> +            .map(|(_x, y)| y)
Next time don't mark it resolved if the fix is not pushed

2021-03-02 19:26 UTC, cecton commented on src/app.rs
> +    ListItem,
No the list will be the main page. Why do you want a home page for? XD "welcome to the world woooohooo click ok now"

2021-03-02 19:29 UTC, cecton commented on src/app.rs
> +                                                <ListItem candidate={x} />
It's a list item of what? XD Imagine you had 10 different lists, you would all call them "list" and "list item"?

2021-03-02 19:37 UTC, yozhgoor commented on src/app.rs
> +    ListItem,
For some explication about the site, the use of the site and how to add a profile ?

2021-03-02 19:40 UTC, yozhgoor commented on src/app.rs
> +    ListItem,
with a pretty link to the list of candidate :D

2021-03-02 19:55 UTC, cecton commented on src/app.rs
> +    ListItem,
The site will be self explanatory. The user don't need to know how to add a profile, the instructions will be on GitHub

2021-03-02 20:11 UTC, yozhgoor commented on src/app.rs
> +    ListItem,
Ok, i get it!

2021-03-03 02:26 UTC, cecton commented on src/app.rs
> +                                                <ListCandidate candidate={x} />
I think you miss the point that I'm not talking literally/completely about things but sometimes I talk about abstract things. This is to show you how to reason about things.

If you call your component CandidateList, it is wrong because it's not a list but an item of a list.

If you call it ListItem, now it is wrong because it's to generic and you might have name collision as soon as you make another list component for something else than a candidate.

Naming things is hard. You have one life left.

2021-03-03 02:28 UTC, cecton commented on src/app.rs
>      Home,
You still have a duplicated variant

2021-03-03 06:40 UTC, yozhgoor commented on src/app.rs
> +                                                <ListCandidate candidate={x} />
So ProfileListItem ? Because we have a candidate show in a profile, and you can go to the profile with a click on a item in the profile list

2021-03-03 09:13 UTC, cecton approved these changes

2021-03-03 09:23 UTC, merged